
package com.xkcoding.orm.mybatis.wsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "WeatherServiceImpl", targetNamespace = "http://service.mybatis.orm.xkcoding.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface WeatherServiceImpl {


    /**
     * @return returns java.util.List<com.xkcoding.orm.mybatis.wsdl.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllWebServiceInface", targetNamespace = "http://service.mybatis.orm.xkcoding.com/", className = "com.xkcoding.orm.mybatis.wsdl.FindAllWebServiceInface")
    @ResponseWrapper(localName = "findAllWebServiceInfaceResponse", targetNamespace = "http://service.mybatis.orm.xkcoding.com/", className = "com.xkcoding.orm.mybatis.wsdl.FindAllWebServiceInfaceResponse")
    @Action(input = "http://service.mybatis.orm.xkcoding.com/WeatherServiceImpl/findAllWebServiceInfaceRequest", output = "http://service.mybatis.orm.xkcoding.com/WeatherServiceImpl/findAllWebServiceInfaceResponse")
    public List<User> findAllWebServiceInface();

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryWeatherByCityName", targetNamespace = "http://service.mybatis.orm.xkcoding.com/", className = "com.xkcoding.orm.mybatis.wsdl.QueryWeatherByCityName")
    @ResponseWrapper(localName = "queryWeatherByCityNameResponse", targetNamespace = "http://service.mybatis.orm.xkcoding.com/", className = "com.xkcoding.orm.mybatis.wsdl.QueryWeatherByCityNameResponse")
    @Action(input = "http://service.mybatis.orm.xkcoding.com/WeatherServiceImpl/queryWeatherByCityNameRequest", output = "http://service.mybatis.orm.xkcoding.com/WeatherServiceImpl/queryWeatherByCityNameResponse")
    public String queryWeatherByCityName(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
